#!/usr/bin/env bash
# Script installs NGINX on web server
# NGINX should be listening to port 80
# Returns "Hello World" when querying NGINX at its root using curl

sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
