#!/usr/bin/env bash
# Script contains error page 404 for server

sudo apt-get update
sudo apt-get install -y nginx

# echo "Hello World!" > /var/www/html/index.html
echo "301 Moved Permanently" >> /var/www/html/index.html
echo "Ceci n'est pas une page" >> /var/www/html/404.html
sed -i '38i\rewrite ^/redirect_me  https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '39i\error_page 404 /404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
