#!/usr/bin/env bash
# Script configures nginx so that HTTP response contains custom header
# for web-01 and web-02
# name of the custom HTTP header is X-Served-by

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
