#!/usr/bin/env bash
# Displays numbers from 1 to 100
# Display FizzBuzz when multiple of 3 and 5
# Display Fizz when multiple of 3
# Display Buzz when multiple of 5
for ((i = 1; i <=100; i++))
do
  if [[ $((i % 3)) = 0 && $((i % 5)) = 0 ]]; then
      echo FizzBuzz
    elif [ $((i % 3)) = 0 ]; then
      echo Fizz
    elif [ $((i % 5)) = 0 ]; then
      echo Buzz
    else
      echo "$i"
  fi
done
