#!/usr/bin/env bash
# Loops displays "Best School";"bad, good" luck
i=0
while [ $i -lt 20 ]
do
    ((i++))
    echo "$i"
    if [ "$i" -eq 4 ]
    then
        echo "bad luck from China"
    elif [ "$i" -eq 9 ]
    then
        echo "bad luck from Japan"
    elif [ "$i" -eq 17 ]
    then
        echo "bad luck from Italy"
    fi
done
