#!/usr/bin/env bash
# Provides information about school
file="school"
if [ -e $file ]; then
    echo $file file exists
    if [ -s $file ]; then
        echo $file file is not empty
        if [ -d $file ]; then
            echo $file is a regular file
        fi
    else
        echo $file file is empty
    fi
else
    echo $file file does not exist
fi
