#!/usr/bin/env bash                                                             
# This script that accepts one argument whoami                                       
# It runs the 'whoami' command under the user passed as argument
if [[ $# -ne 1 ]]; then
	exit 1
fi
sudo -u "$1" whoami
