#!/usr/bin/env bash                                                             
# This script that accepts one argument whoami                                       
# It runs the 'whoami' command under the user passed as argument
if [[ $# -eq 1 ]]
then
	sudo -u "$1" whoami
else
	whoami
fi
