#!/usr/bin/env bash
# Script uses whoami
username="$1"
user_home=$(getent passwd "$username" | cut -d: -f6)

if [[ -n "$user_home" ]]; then
  username=$(sudo -u "$username" whoami)
fi

echo "$username"
