#!/usr/bin/env bash

# Update nginx configuration file
sed -i 's/user .*/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen .*/listen 8080;/g' /etc/nginx/nginx.conf

# Restart nginx service
service nginx restart
